name: belajarflutter
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  getwidget: ^7.0.0
  flutter_rating_bar: ^4.0.1
  loading_animation_widget: ^1.3.0
  chips_choice: ^3.0.1
  intl: ^0.18.1 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/COZY.png
    - assets/images/grooming.png
    - assets/images/boarding.png
    - assets/images/vaksin.png
    - assets/images/antarjemput.png
    

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf